services:

  ## filebrowser ###
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser
    restart: always
    volumes:
      - /:/srv #change user to your name or use ~/
      - ${COMMON_CONFIG_PATH}/filebrowser:/database.db #create the filebrowser.db file before deploying
    ports:
      - 8095:80
    user: ${UID}:${GID}
    networks:
      media-apps:
        ipv4_address: 192.168.100.3

  ### transmission ###
  transmission:
    container_name: transmission
    image: lscr.io/linuxserver/transmission:latest
    restart: unless-stopped
    volumes:
      - ${COMMON_CONFIG_PATH}/transmission/config:/config
      - ${TEMP_DOWNLOAD_PATH}/transmission:/downloads/incomplete #optional
      - ${ALL_MEDIA_PATH}:/downloads/complete
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
      - TRANSMISSION_WEB_HOME= #optional
      - USER=${TR_USERNAME} #optional
      - PASS=${TR_PASSWORD} #optional
      - WHITELIST= #optional
      - PEERPORT= #optional
      - HOST_WHITELIST= #optional
    networks:
      media-apps:
        ipv4_address: 192.168.100.4

  ### jellyfin ###
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: host
    restart: always
    volumes:
      - ${COMMON_CONFIG_PATH}/jellyfin/config:/config
      - ${COMMON_CONFIG_PATH}/jellyfin/cache:/cache
      - ${ALL_MEDIA_PATH}:/media
    # networks:
    #   media-apps:
    #     ipv4_address: 192.168.100.5

  ### ariang ###
  ariang:
    image: hurlenko/aria2-ariang
    container_name: ariang
    ports:
      - 443:8080
    volumes:
      - ${COMMON_CONFIG_PATH}/aria2:/aria2/conf
      - ${ALL_MEDIA_PATH}:/aria2/data
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - RPC_SECRET=${AG_SECRET}
      - ARIA2RPCPORT=443
      - BASIC_AUTH_USERNAME=${AG_USERNAME}
      - BASIC_AUTH_PASSWORD=${AG_PASSWORD}
    restart: always
    networks:
      media-apps:
        ipv4_address: 192.168.100.6

  ### qbittorrent ###
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ${COMMON_CONFIG_PATH}/qbittorrent:/config
      # - ${QBT_DOWNLOADS_INCOMPLETE_PATH}:/downloads/incomplete
      # - ${QBT_DOWNLOADS_PATH}:/data/downloads
      - ${TEMP_DOWNLOAD_PATH}/qbittorrent:/temp-downloads
      # - ${ALL_MEDIA_PATH}:/data:rw
      - ${ALL_MEDIA_PATH}:/data
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks:
      media-apps:
        ipv4_address: 192.168.100.7

  ### radarr ###
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
    volumes:
      - ${COMMON_CONFIG_PATH}/radarr:/config
      # - ${RD_MOVIES_PATH}:/movies #optional
      # - ${ALL_MEDIA_PATH}:/data:rw #optional
      - ${ALL_MEDIA_PATH}:/data
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      media-apps:
        ipv4_address: 192.168.100.8

  ### sonarr ###
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
    volumes:
      - ${COMMON_CONFIG_PATH}/sonarr:/config
      # - ${SO_TV_PATH}:/tv #optional
      # - ${ALL_MEDIA_PATH}:/data:rw #optional
      - ${ALL_MEDIA_PATH}:/data
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      media-apps:
        ipv4_address: 192.168.100.9

  # ### bazarr ###
  # bazarr:
  #   image: lscr.io/linuxserver/bazarr:latest
  #   container_name: bazarr
  #   environment:
  #     - PUID=${UID}
  #     - PGID=${GID}
  #     - TZ=${TZ}
  #   volumes:
  #     - ${BZ_CONFIG_PATH}:/config
  #     - ${BZ_MOVIES_PATH}:/movies #optional
  #     - ${BZ_TV_PATH}:/tv #optional
  #   ports:
  #     - ${BZ_WEBUI_PORT}:${BZ_WEBUI_PORT}
  #   restart: unless-stopped
  #   networks:
  #     media-apps:
  #       ipv4_address: 192.168.100.10

  ### prowlarr ###
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
    volumes:
      - ${COMMON_CONFIG_PATH}/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      media-apps:
        ipv4_address: 192.168.100.11

  ### flaresolverr ###
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${FL_LOG_LEVEL}
      - LOG_FILE=${FL_LOG_FILE}
      - LOG_HTML=${FL_LOG_HTML}
      - CAPTCHA_SOLVER=${FL_CAPTCHA_SOLVER}
      - TZ=${TZ}
    ports:
      - 8191:8191
    volumes:
      - ${COMMON_CONFIG_PATH}/flaresolverr:/config
    restart: unless-stopped
    networks:
      media-apps:
        ipv4_address: 192.168.100.12

networks:
  media-apps:
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24
